import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { RouterOutputs, api } from "~/utils/api"

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;

  return <div className="flex gap-4 w-full">
    <img src={user.profileImageUrl} alt="Profile Image" className="w-16 h-16 rounded-full" />
    <input className="bg-transparent grow outline-none" placeholder="Type your message..." />
  </div>
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number]

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div className="flex p-4 border-b border-slate-400 gap-4" key={post.id}>
      <img className="w-16 h-16 rounded-full" src={author?.profilePicture} />
      <div className="flex flex-col">
        <div className="flex text-slate-400 gap-1">
          <span>{`@${author?.name}`}</span><span>{`• ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

export default function Home() {
  const user = useUser();
  console.log(user)
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return (<div>Loading...</div>)
  if (!data) return (<div>Something went wrong...</div>)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <SignOutButton />
        <div className="w-full h-full md:max-w-2xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && (<div className="flex justify-center">
              <SignInButton />
            </div>)}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data.map((fullPost) =>
              <PostView {...fullPost} key={fullPost.post.id} />
            )}
          </div>
        </div>
      </main >
    </>
  );
}
