import Head from "next/head";
import Image from "next/image";
import { useSession, signIn, signOut } from "next-auth/react";
import { useState } from "react";

import { api } from "~/utils/api"
import type { RouterOutputs } from "~/utils/api"

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingPage } from "~/components/loading";
dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { data: session } = useSession();
  const [message, setMessage] = useState("")
  const ctx = api.useContext();
  const { mutate } = api.posts.create.useMutation({
    onSuccess: () => {
      setMessage("");
      void ctx.posts.getAll.invalidate();
    }
  });

  console.log(session?.user)
  if (!session?.user) return null;

  return <div className="flex gap-4 w-full">
    <Image src={session.user.image} alt="Profile Image" className="w-16 h-16 rounded-full" width={56} height={56} />
    <input
      type="text"
      value={message}
      onChange={(e) => setMessage(e.target.value)}
      className="bg-transparent grow outline-none"
      placeholder="Type your message..." />
    <button onClick={() => mutate({ name: session.user.name, content: message })
    }>Send</button>
  </div>
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number]

const PostView = (props: PostWithUser) => {
  return (
    <div className="flex p-4 border-b border-slate-400 gap-4" key={props.id}>
      <Image className="w-16 h-16 rounded-full" src={props.image} alt={`@${props.name}'s profile picture`} width={56} height={56} />
      <div className="flex flex-col">
        <div className="flex text-slate-400 gap-1">
          <span>{`@${props?.name}`}</span><span>{`• ${dayjs(props.createdAt).fromNow()}`}</span>
        </div>
        <span className="text-2xl">{props.content}</span>
      </div>
    </div>
  )
}

const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (postsLoading) return <LoadingPage />;
  console.log(data)

  if (!data) return <div>Something went wrong!</div>;
  return (
    <div className="flex flex-col">
      {data.map((props) =>
            <div className="flex p-4 border-b border-slate-400 gap-4" key={props.id}>
            <Image className="w-16 h-16 rounded-full" src={props?.image} alt={`@${props.name}'s profile picture`} width={56} height={56} />
            <div className="flex flex-col">
              <div className="flex text-slate-400 gap-1">
                <span>{`@${props?.name}`}</span><span>{`• ${dayjs(props.createdAt).fromNow()}`}</span>
              </div>
              <span className="text-2xl">{props.content}</span>
            </div>
          </div>
      )}
    </div>
  )
}

export default function Home() {
  const { data: user } = useSession();

  // if (!userLoaded) return <div />

  return (
    <>
      <Head>
        <title>Unite</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
      <div className="flex justify-center">
        <div className="w-full h-full md:max-w-2xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-4">
            {!user && (<div className="flex justify-center p-5">
              <button onClick={() => void signIn("google")}>Sign In</button>
            </div>)}
            {user && <CreatePostWizard />}
          </div>
          <Feed />
        </div>
      </div >
      </div>
    </>
  );
}
